apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: tsdb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: quant
    database: quant
    isDefault: true
    editable: false
    secureJsonData:
      password: "$__env{TSDB_PASSWORD}"
    jsonData:
      database: quant
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
